FROM debian:stable-slim

LABEL maintainer="Bhumjate S. <bsthun@gmail.com>"

# Add entrypoint script
ADD entrypoint.sh /usr/local/bin

# Install OpenSSH
RUN apt update \
	&& apt install -y openssh-server \
	&& apt-get clean \
	&& rm -rf /tmp/* /etc/ssh/ssh_host_key \
	&& sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
	&& sed -ie 's/#Port 22/Port 22/g' /etc/ssh/sshd_config \
	&& mkdir -p /run/sshd \
	&& chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 22
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]