FROM alpine:edge

MAINTAINER Bhumjate S. <bsthun@gmail.com>

# Add entrypoint script
ADD entrypoint.sh /usr/local/bin

# Install OpenSSH
RUN apk add --update openssh \
  && rm -rf /tmp/* /var/cache/apk/* \
  && sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
  && sed -ie 's/#Port 22/Port 22/g' /etc/ssh/sshd_config \
  && mkdir -p /run/sshd \
  && chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 22
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/sbin/sshd","-D"]